# Generated by Django 2.1.3 on 2020-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_auto_20190429_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='session_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='session_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
